DriveTank:
  modifiers: { deadzone: 0.1, exponent: 2.0 }

PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.4, right: -0.4 }
  holdPowers: { left: 0.1, right: 0.1 }
  jamDetectPeriod: 0.05
  unjamPeriod: 0.2
  afterUnjamWait: 0.5
  finishDetectPeriod: 0.0

PickerRelease:
  powers: { left: -1.0, right: -1.0 }

PivotLeft: { class: PivotAnglePreset, preset: LEFT }
PivotCenter: { class: PivotAnglePreset, preset: CENTER }
PivotRight: { class: PivotAnglePreset, preset: RIGHT }

$LiftHome:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: HOME }
$LiftPick:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: PICK }
$LiftSwitch:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SWITCH }
$LiftScaleLow:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_LOW }
$LiftScaleHigh:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_HIGH }

$PrepareLiftMovement:
  - { class: Log, message: "Preparing to move lift" }
  - PickerRetract
  - PivotCenter
  - WaitForCenter

LiftContinuous:
  pivotSweepPower: 0.2
  startSweepAngle: 5.0
  sweepTimeoutSeconds: 5.0
TestDriveStraight:
  class: DriveStraight
  speed: 48.0
  distance: 12.0
  maxAcceleration: 84.0
TestDriveRotate:
  class: DriveRotate
  angle: 90
  rotationSpeed: 30
  maxAcceleration: 30


^Drive.Straight: { speed: 84.0, endSpeed: 0.0, maxAcceleration: 140 }
^Drive.Rotate: { rotationSpeed: 180, maxAcceleration: 400 }
^Drive.Arc: { speed: 40.0, endSpeed: 0.0, maxAcceleration: 100, maxAngularAcceleration: 400 }