PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.2, right: -0.2 }
  holdPowers: { left: 0.05, right: 0.05 }
  jamDetectPeriod: 0.0
  unjamPeriod: 0.2
  afterUnjamWait: 1.0
  finishDetectPeriod: 0.0
