DriveTank:
  modifiers: { deadzone: 0.1, exponent: 2.0 }

PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.4, right: -0.4 }
  holdPowers: { left: 0.15, right: 0.15 }
  jamDetectPeriod: 0.05
  unjamPeriod: 0.2
  afterUnjamWait: 0.5
  finishDetectPeriod: 0.0

PickerRegrip:
  gripPower: 1
  holdPower: 0.15

PickerRelease:
  powers: { left: -0.7, right: -0.7 }

$PickerReleaseTeleop:
  - PickerQuickDeploy
  - PivotCenter
  - WaitForCenter

PivotLeft: { class: PivotAnglePreset, preset: LEFT }
PivotCenter: { class: PivotAnglePreset, preset: CENTER }
PivotRight: { class: PivotAnglePreset, preset: RIGHT }
^WaitForAngle: { tolerance: 5.0 }
WaitForAngle: {}
WaitForLeft: { class: WaitForAngle, preset: LEFT, tolerance: 15.0 }
WaitForRight: { class: WaitForAngle, preset: RIGHT, tolerance: 15.0 }

WaitForHeight: { tolerance: 1 }
$LiftHome:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: HOME }
$LiftPick:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: PICK }
$LiftSwitch:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SWITCH }
$LiftScaleLow:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_LOW }
$LiftScaleHigh:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_HIGH }

$PrepareLiftMovement:
  - { class: Log, message: "Preparing to move lift" }
  - PickerRetract
  - PivotCenter
  - WaitForCenter

LiftContinuous:
  pivotSweepPower: 0.15
  startSweepAngle: 3.0
  sweepTimeoutSeconds: 5.0
$TestDrive:
  - { class: DriveStraight, angle: 0.0, distance: -144.0, endSpeed: 60.0 }
  - { class: DriveArc, angle: -90, radius: -48, endSpeed: 60 }
  - { class: DriveStraight, distance: -138, angle: -90, endSpeed: 60 }
#  maxAcceleration: 84.0
#TestDriveRotate:
#  class: DriveRotate
#  angle: 90
#  rotationSpeed: 30
#  maxAcceleration: 30


^DriveStraight: { speed: 100.0, endSpeed: 0.0, maxAcceleration: 100 }
^DriveRotate: { rotationSpeed: 180, maxAcceleration: 400 }
^DriveArc: { speed: 60.0, endSpeed: 0.0, maxAcceleration: 100, maxAngularAcceleration: 400 }

PickerQuickDeploy:
  kickPower: 1
  timeBeforeKick: 0.1
  timeBeforeRetract: 0.4
  timeToKick: 0.6

#############################################################################################
#                                                                                           #
#                                  AUTO SEQUENCES                                           #
#                                                                                           #
#############################################################################################
NoAuto: { class: Log, level: WARN, message: "No auto was selected."}
DebugChooserAuto: { class: Log, level: INFO, message: "Woohoo! The autochooser works!"}
LineCrossAuto: { class: DriveStraight, distance: -125 }

$CommonDriveSequence:
  - { parallel: true, name: PickerRegrip }
  - { parallel: true, name: $LiftSwitch }
  - { class: DriveStraight, distance: -144, endSpeed: 100.0 }

$Scale:
  - $CommonDriveSequence
  - { class: AutoSelector, type: STARTING_POSITION, left: ScaleLeftChooser, center: ScaleCenterChooser, right: ScaleRightChooser}

$ScaleSwitch:
  - $CommonDriveSequence
  - { class: AutoSelector, type: STARTING_POSITION, left: ScaleSwitchAutoLeftChooser, center: ScaleSwitchAutoCenterChooser, right: ScaleSwitchAutoRightChooser}

ScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $ScaleAutoCloseL, R: $ScaleAutoFarR }
ScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $ScaleAutoFarL, R: $ScaleAutoCloseR }

ScaleSwitchAutoLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: ScaleSwitchAutoLeftLScaleChooser, R: ScaleSwitchAutoLeftRScaleChooser }
ScaleSwitchAutoRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: ScaleSwitchAutoRightLScaleChooser, R: ScaleSwitchAutoRightRScaleChooser }

ScaleSwitchAutoLeftLScaleChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $ScaleSwitchAutoLeftLScaleLSwitch, R: $ScaleSwitchAutoLeftLScaleRSwitch }
ScaleSwitchAutoLeftRScaleChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $ScaleSwitchAutoLeftRScaleLSwitch, R: $ScaleSwitchAutoLeftRScaleRSwitch }
ScaleSwitchAutoRightLScaleChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $ScaleSwitchAutoRightLScaleLSwitch, R: $ScaleSwitchAutoRightLScaleRSwitch }
ScaleSwitchAutoRightRScaleChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $ScaleSwitchAutoRightRScaleLSwitch, R: $ScaleSwitchAutoRightRScaleRSwitch }

$ScaleSwitch:
  - $CommonDriveSequence

$SmartScale:
  - $CommonDriveSequence

$LiftSequenceScaleLowLeft:
  - $LiftScaleLow
  - WaitForHeight
  - PivotLeft

$LiftSequenceScaleLowRight:
  - $LiftScaleLow
  - WaitForHeight
  - PivotRight

$LiftSequenceScaleLowRight2:
  - PickerPick
  - $LiftScaleLow
  - WaitForHeight
  - PivotRight

$SubsequenceScaleAutoFarL:
  - { class: DriveStraight, distance: -12, endSpeed: 100.0 }
  - { class: DriveArc, angle: -90, radius: -48, endSpeed: 60 }
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - { class: DriveStraight, distance: -130, angle: -90, endSpeed: 60 }
  - { class: DriveArc, radius: -48, angle: -30, speed: 60.0, endSpeed: 60.0 }
  - { class: DriveStraight, angle: -30, distance: -24, speed: 60 }
  - WaitForLeft
  - { class: PickerQuickDeploy, kickPower: 0.7 }
  - PivotCenter
  - WaitForCenter
  - $LiftHome
  - { parallel: true, name: PickerPick }
  - { class: Wait, period: 0.5 }
#  - { class: DriveArc, arcLength: 60, angle: 0 }
  - { class: DriveStraight, angle: -30, distance: 72 }
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - { class: Wait, period: 0.5 }

$ScaleAutoCloseL:
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - { class: DriveStraight, distance: -144 }
  - WaitForHeight
  - WaitForAngle
  - PickerQuickDeploy
  - PivotCenter
  - $LiftHome
$ScaleAutoCloseR:
  - { parallel: true, name: $LiftSequenceScaleLowRight }
  - { class: DriveStraight, distance: -156 }
  - WaitForRight
  - PickerQuickDeploy
  - PivotCenter
  - $LiftHome
  - { parallel: true, name: $LiftSequenceScaleLowRight2 }
  - { class: DriveArc, angle: 38, arcLength: 118 }
  - { class: DriveArc, angle: 0, arcLength: -118 }
  - WaitForRight
  - PickerQuickDeploy
  - PivotCenter
  - $LiftHome
$ScaleAutoFarL:
  - $SubsequenceScaleAutoFarL
  - { class: DriveStraight, angle: -30, distance: -72 }
  - WaitForLeft
  - PickerQuickDeploy
  - PivotCenter
  - WaitForCenter
  - $LiftHome
#  - WaitForRight
#  - PickerQuickDeploy
#  - PivotCenter
#  - $LiftHome
$ScaleSwitchAutoRightLScaleLSwitch:
  - $SubsequenceScaleAutoFarL
  - PickerRetract
  - { class: DriveStraight, angle: 0, distance: 6 }
  - { class: PickerQuickDeploy, timeBeforeKick: 0, timeToKick: .4, timeBeforeRetract: 0 }
