DriveTank:
  modifiers: { deadzone: 0.1, exponent: 2.0 }

PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.4, right: -0.4 }
  holdPowers: { left: 0.1, right: 0.1 }
  jamDetectPeriod: 0.05
  unjamPeriod: 0.2
  afterUnjamWait: 0.5
  finishDetectPeriod: 0.0

PickerRelease:
  powers: { left: -1.0, right: -1.0 }

PivotLeft: { class: PivotAnglePreset, preset: LEFT }
PivotCenter: { class: PivotAnglePreset, preset: CENTER }
PivotRight: { class: PivotAnglePreset, preset: RIGHT }

$LiftHome:
#  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: HOME }
$LiftPick:
#  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: PICK }
$LiftSwitch:
#  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SWITCH }
$LiftScaleLow:
#  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_LOW }
$LiftScaleHigh:
#  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_HIGH }

$PrepareLiftMovement:
  - { class: Log, message: "Preparing to move lift" }
  - PickerRetract
  - PivotCenter
  - WaitForCenter

LiftContinuous:
  pivotSweepPower: 0.1
  startSweepAngle: 3.0
  sweepTimeoutSeconds: 5.0
TestDriveStraight:
  class: DriveStraight
  speed: 48.0
  distance: 12.0
  maxAcceleration: 84.0
TestDriveRotate:
  class: DriveRotate
  angle: 90
  rotationSpeed: 30
  maxAcceleration: 30


^DriveStraight: { speed: 84.0, endSpeed: 0.0, maxAcceleration: 140 }
^DriveRotate: { rotationSpeed: 180, maxAcceleration: 400 }
^DriveArc: { speed: 40.0, endSpeed: 0.0, maxAcceleration: 100, maxAngularAcceleration: 400 }
WaitForHeight: { tolerance: 1 }
WaitForAngle: { tolerance: 0.5 }

PickerQuickDeploy:
  kickPower: 1
  timeBeforeKick: 0.2
  timeBeforeRetract: 0.6
  timeToKick: 0.8

#############################################################################################
#                                                                                           #
#                                  AUTO SEQUENCES                                           #
#                                                                                           #
#############################################################################################
NoAuto: { class: Log, level: WARN, message: "No auto was selected."}
LineCrossAuto: { class: DriveStraight, distance: -125 }

$LiftSequence:
  - $LiftScaleLow
#  - WaitForHeight
  - PivotLeft

$ScaleAutoL:
  - { parallel: true, name: $LiftSequence }
  - { class: DriveStraight, distance: -288 }
  - WaitForHeight
  - WaitForAngle
  - PickerQuickDeploy
  - PivotCenter
  - $LiftHome
