DriveTank:
  modifiers: { deadzone: 0.1, exponent: 2.0 }

PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.25, right: -0.25 }
  holdPowers: { left: 0.15, right: 0.15 }
  jamDetectPeriod: 0.1
  unjamPeriod: 0.2
  afterUnjamWait: 0.5
  finishDetectPeriod: 0.0

PickerRegrip:
  gripPower: 1
  holdPower: 0.3

PickerRelease:
  powers: { left: -0.7, right: -0.7 }

^PickerQuickDeploy:
  kickPower: 1
  timeBeforeKick: 0.1
  timeBeforeRetract: 0.4
  timeToKick: 0.6

PickerQuickDeploy:
  kickPower: 0.8
  timeBeforeKick: 0.1
  timeBeforeRetract: 0.4
  timeToKick: 0.6

PickerAutoDeploy:
  { class: PickerQuickDeploy, timeBeforeKick: 0.2, kickPower: 0.6, timeToKick: 0.8 }

PickerSwitchDeploy:
  { class: PickerQuickDeploy, timeBeforeKick: 0, timeToKick: .6, timeBeforeRetract: 0 }

$PickerReleaseHard:
  - { class: PickerQuickDeploy, kickPower: 0.8 }
  - PivotCenter
#  - WaitForLock

$PickerReleaseMedium:
  - { class: PickerQuickDeploy, timeBeforeKick: 0.2, kickPower: 0.6, timeToKick: 0.8 }
  - PivotCenter
#  - WaitForLock

PickerReleaseSoft:
  { class: PickerRelease, powers: { left: -0.4, right: -0.4 } }

PickerSmartDeploy:
  class: PickerSmartDeploy
  powers:
    SOFT: { kickPower: 0.4, timeBeforeKick: 0.3, timeBeforeRetract: 0.8, timeToKick: 1.0 }
    MEDIUM: { kickPower: 0.6, timeBeforeKick: 0.2, timeBeforeRetract: 0.4, timeToKick: 0.8 }
    HARD: { kickPower: 0.8, timeBeforeKick: 0.2, timeBeforeRetract: 0.4, timeToKick: 0.6 }

PivotLeft: { class: PivotAnglePreset, preset: LEFT }
PivotHalfLeft: { class: PivotAnglePreset, preset: HALF_LEFT }
PivotCenter: { class: PivotAnglePreset, preset: CENTER }
PivotHalfRight: { class: PivotAnglePreset, preset: HALF_RIGHT }
PivotRight: { class: PivotAnglePreset, preset: RIGHT }
^WaitForAngle: { tolerance: 5.0 }
WaitForAngle: {}
WaitForLeft: { class: WaitForAngle, preset: LEFT, tolerance: 20.0 }
WaitForRight: { class: WaitForAngle, preset: RIGHT, tolerance: 20.0 }
WaitForCenter: { class: WaitForAngle, preset: CENTER, tolerance: 20.0 }

WaitForHeight: { tolerance: 1 }
LiftHome: { class: LiftHeightPreset, preset: HOME }
$LiftHome:
  - $PrepareLiftMovement
  - LiftHome
$LiftPick:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: PICK }
$LiftSwitch:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SWITCH }
$LiftScaleLow:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_LOW }
$LiftScaleHigh:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SCALE_HIGH }
$LiftSwitchLow:
  - $PrepareLiftMovement
  - { class: LiftHeightPreset, preset: SWITCH_LOW }

$PrepareLiftMovement:
  - { class: Log, message: "Preparing to move lift" }
  - PickerRetract
  - PivotCenter
  - WaitForCenter

LiftContinuous:
  pivotSweepPower: 0.2
  startSweepAngle: 5.0
  sweepTimeoutSeconds: 5.0
  lockedPeriod: 0.1
  sliderTolerance: 2
  sliderThreshold: 1
  knobTolerance: 5.0
$TestDrive:
#  - { class: DriveStraight, angle: 0.0, distance: -144.0, endSpeed: 60.0 }
#  - { class: DriveArc, angle: -90, radius: -48, endSpeed: 60 }
#  - { class: DriveStraight, distance: -138, angle: -90, endSpeed: 60 }
  - class: SetPose
    x: 0.0
    y: 0.0
    yaw: -90
  - class: DrivePath
    speed: 140
    arcSpeed: 60
    radius: 36
    reverse: true
    path:
      - { x: 0, y: 0 }
      - { x: 0, y: 78 }
      - { x: 78, y: 78 }
      - { x: 78, y: 0 }
      - { x: 0, y: 0 }

PickerAutoPick:
  velocity: 0.4
  maxDriveDistance: 84.0

$AutoPick:
  - { parallel: true, name: PickerPick }
  - PickerAutoPick

$PickerAutoPick:
  - { parallel: true, name: PickerPick }
  - PickerAutoPick
  - { class: Cancel, command: PickerPick }

#  maxAcceleration: 84.0
#TestDriveRotate:
#  class: DriveRotate
#  angle: 90
#  rotationSpeed: 30
#  maxAcceleration: 30

ElevatorsDeploy:
  retractTime: .2
ElevatorsLiftLeft:
  flapPower: 1.0

^DriveStraight: { speed: 100.0, endSpeed: 0.0, maxAcceleration: 100 }
^DriveRotate: { rotationSpeed: 180, maxAcceleration: 400 }
^DriveArc: { speed: 60.0, endSpeed: 0.0, maxAcceleration: 100, maxAngularAcceleration: 400 }
^DrivePath: { speed: 100, arcSpeed: 60, radius: 30 }
#############################################################################################
#                                                                                           #
#                                  AUTO SEQUENCES                                           #
#                                                                                           #
#############################################################################################
NoAuto: { class: Log, level: WARN, message: "No auto was selected."}
DebugAfterHeld: { class: Log, level: INFO, message: "Woohoo! afterHeld works!"}
LineCrossAuto: { class: DriveStraight, distance: -125 }

SetPoseLeft:
  class: SetPose
  x: -115
  y: 19
  yaw: -90

SetPoseRight:
  class: SetPose
  x: 115
  y: 19
  yaw: -90

SetPoseCenter:
  class: SetPose
  x: 0
  y: 19
  yaw: 90

$CommonLiftSequence:
  - PickerRegrip
  - { class: Wait, period: 0.25 }
  - $LiftSwitch

$CommonDriveSequence:
  - { parallel: true, name: $CommonLiftSequence }
  - { class: DriveStraight, distance: -90, endSpeed: 100.0, speed: 100 } # 100

Scale:
  { class: AutoSelector, type: STARTING_POSITION, left: $ScaleStartLeft, right: $ScaleStartRight}

ScaleSwitch:
  { class: AutoSelector, type: STARTING_POSITION, left: $ScaleSwitchLeft, right: $ScaleSwitchRight}

SmartScale:
  { class: AutoSelector, type: STARTING_POSITION, left: $SmartScaleLeft, right: $SmartScaleRight }

$ScaleStartLeft:
  - SetPoseLeft
  - $CommonDriveSequence
  - ScaleLeftChooser

$ScaleStartRight:
  - SetPoseRight
  - $CommonDriveSequence
  - ScaleRightChooser

ScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartLeftScaleLeftScaleLeft, R: $AutoStartLeftScaleRightScaleRight }
ScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: $AutoStartRightScaleLeftScaleLeft, R: $AutoStartRightScaleRightScaleRight }

$ScaleSwitchLeft:
  - SetPoseLeft
  - $CommonDriveSequence
  - ScaleSwitchStartLeftChooser

$ScaleSwitchRight:
  - SetPoseRight
  - $CommonDriveSequence
  - ScaleSwitchStartRightChooser

ScaleSwitchStartLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: StartLeftScaleLeftChooser, R: StartLeftScaleRightChooser }
ScaleSwitchStartRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: StartRightScaleLeftChooser, R: StartRightScaleRightChooser }

StartLeftScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartLeftScaleLeftSwitchLeft, R: $AutoStartLeftScaleLeftSwitchRight }
StartLeftScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartLeftScaleRightSwitchLeft, R: $AutoStartLeftScaleRightSwitchRight }
StartRightScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartRightScaleLeftSwitchLeft, R: $AutoStartRightScaleLeftSwitchRight }
StartRightScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartRightScaleRightSwitchLeft, R: $ AutoStartRightScaleRightSwitchRight }

$SmartScaleLeft:
  - SetPoseLeft
  - $CommonDriveSequence
  - SmartScaleStartLeftChooser

$SmartScaleRight:
  - SetPoseRight
  - $CommonDriveSequence
  - SmartScaleStartRightChooser

SmartScaleStartLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: StartLeftScaleLeftChooser, R: StartLeftScaleRightChooser }
SmartScaleStartRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 1, L: StartRightScaleLeftChooser, R: StartRightScaleRightChooser }

SmartScaleStartLeftScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartLeftScaleLeftScaleLeft, R: $AutoStartLeftScaleLeftScaleLeft }
SmartScaleStartLeftScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: SlowDown, R: SlowDown }
SmartScaleStartRightScaleLeftChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: SlowDown, R: SlowDown }
SmartScaleStartRightScaleRightChooser: { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $AutoStartRightScaleRightScaleRight, R: $ $AutoStartRightScaleRightScaleRight }

SlowDown:
  class: DriveStraight
  distance: -48
  speed: 30.0

$CenterAuto:
  - SetPoseCenter
  - { class: DriveStraight, distance: 12, speed: 100, endSpeed: 70.0 }
#  - { parallel: true, name: $LiftSwitchLow }
  - { class: AutoSelector, type: FIELD_CONFIGURATION, object: 0, L: $CenterAutoLSwitch, R: $CenterAutoRSwitch }

$CenterAutoLSwitch:
  - { class: DriveArc, arcLength: 55, angle: -45, speed: 100, endSpeed: 100.0 }
  - { class: DriveArc, arcLength: 50, angle: 0, speed: 100 }
  - PickerSwitchDeploy
  - { parallel: true, name: PickerPick }
  - { class: DriveStraight, angle: 0, distance: -48 }
  - { class: DriveRotate, angle: 60 }
  - { class: DriveStraight, angle: 60, distance: 44.0 }
#  - { class: DriveArc, arcLength: -58, speed: 100, angle: 65 }
#  - { class: DriveStraight, angle: 65, distance: 54.0 }
  - WaitForCube
  - { class: DriveStraight, angle: 60, distance: -4.0 }
  - { class: WaitFor, command: PickerPick }
  - { class: DriveStraight, angle: 60, distance: -40 }
  - { class: DriveRotate, angle: 0 }
  - { class: DriveStraight, angle: 0, distance: 50.0 }
#  - { class: DriveStraight, angle: 65, distance: -50.0 }
#  - { class: DriveArc, arcLength: 63, speed: 100, angle: 0 }
  - PickerSwitchDeploy
  - { parallel: true, name: PickerPick }
#  - { class: DriveArc, arcLength: -58, speed: 100, angle: 65 }
#  - { class: DriveStraight, angle: 65, distance: 54.0 }
  - { class: DriveStraight, angle: 0, distance: -36 }
  - { class: DriveRotate, angle: 60 }
  - { class: DriveStraight, angle: 60, distance: 46.0 }

$CenterAutoRSwitch:
  - { class: DriveArc, arcLength: 55, angle: 48, speed: 100, endSpeed: 100.0 }
  - { class: DriveArc, arcLength: 55, angle: 0, speed: 100 }
  - PickerSwitchDeploy
  - { parallel: true, name: PickerPick }
  - { class: DriveStraight, angle: 0, distance: -48 }
  - { class: DriveRotate, angle: -60 }
  - { class: DriveStraight, angle: -60, distance: 44.0 }
#  - { class: DriveArc, arcLength: -53, speed: 100, angle: -65 }
#  - { class: DriveStraight, angle: -65, distance: 50.0 }
  - WaitForCube
  - { class: DriveStraight, angle: -60, distance: -4.0 }
  - { class: WaitFor, command: PickerPick }
  - { class: DriveStraight, angle: -60, distance: -40 }
  - { class: DriveRotate, angle: 0 }
  - { class: DriveStraight, angle: 0, distance: 50.0 }
#  - { class: DriveStraight, angle: -65, distance: -50.0 }
#  - { class: DriveArc, arcLength: 60, speed: 100, angle: 0 }
  - PickerSwitchDeploy
  - { parallel: true, name: PickerPick }
#  - { class: DriveArc, arcLength: -53, speed: 100, angle: -65 }
#  - { class: DriveStraight, angle: -65, distance: 50.0 }
  - { class: DriveStraight, angle: 0, distance: -36 }
  - { class: DriveRotate, angle: -60 }
  - { class: DriveStraight, angle: -60, distance: 42.0 }

$LiftSequenceScaleLowLeft:
  - { class: WaitFor, command: PickerPick }
  - $LiftScaleLow
  - PivotLeft

$LiftSequenceScaleLowRight:
  - { class: WaitFor, command: PickerPick }
  - $LiftScaleLow
  - PivotRight

$StartRightScaleLeft:
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 80
    path:
#      - { x: -115, y: 19 }
      - { x: 115, y: 109 }
      - { x: 115, y: 231, radius: 48 }
      - { x: -60, y: 231, radius: 48 }
      - { x: -102, y: 284 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - $LiftScaleLow
  - PivotLeft
  - WaitForLeft
  - { class: WaitForPath }
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    path:
      - { x: -102, y: 284, speed: 40 }
      - { x: -90, y: 258, radius: 36, speed: 20.0 }
      - { x: -82, y: 226 }
  - WaitForCube

$StartLeftScaleRight:
  - class: DrivePath
    parallel: true
    reverse: true
    speed: 80
    path:
#      - { x: -115, y: 19 }
      - { x: -115, y: 109 }
      - { x: -115, y: 240, radius: 48 }
      - { x: 60, y: 240, radius: 48 }
      - { x: 102, y: 284 }
  - { class: WaitForPath, remainingDistance: 100.0 }
  - $LiftScaleLow
  - PivotRight
  - WaitForRight
  - { class: WaitForPath }
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    path:
      - { x: 102, y: 284, speed: 80 }
      - { x: 90, y: 270, radius: 36, speed: 20.0 }
      - { x: 82, y: 232 }
  - WaitForCube

$StartLeftScaleLeft:
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - class: DrivePath
    reverse: true
    speed: 100
    path:
#      - { x: -115, y: 19 }
      - { x: -115, y: 109 }
      - { x: -115, y: 300 }
  - WaitForLeft
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - WaitForLock
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    parallel: true
    speed: 80
    path:
      - { x: -115, y: 300, speed: 100.0 }
      - { x: -115, y: 280, radius: 36, speed: 100.0 }
      - { x: -90, y: 242, radius: 36, speed: 40.0 }
      - { x: -78, y: 212 }
  - WaitForCube

$StartRightScaleRight:
  - { parallel: true, name: $LiftSequenceScaleLowRight }
  - class: DrivePath
    reverse: true
    speed: 100
    path:
#      - { x: 115, y: 19 }
      - { x: 115, y: 109 }
      - { x: 115, y: 300 }
  - WaitForRight
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - WaitForLock
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    parallel: true
    speed: 80
    path:
      - { x: 115, y: 300, speed: 100.0 }
      - { x: 115, y: 280, radius: 36, speed: 100.0 }
      - { x: 90, y: 230, radius: 36, speed: 40.0 }
      - { x: 78, y: 200 }
  - WaitForCube

$AutoStartLeftScaleLeftScaleLeft:
  - $StartLeftScaleLeft
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - class: DrivePath
    reverse: true
    speed: 40
    path:
      - { x: -78, y: 212 }
      - { x: -90, y: 252, radius: 36 }
      - { x: -110, y: 280 }
  - WaitForLeft
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    parallel: true
    speed: 80
    path:
      - { x: -110, y: 280, speed: 100.0 }
      - { x: -90, y: 240, radius: 36, speed: 40.0 }
      - { x: -52, y: 210 }
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - WaitForCube
  - class: DrivePath
    reverse: true
    speed: 40
    path:
      - { x: -52, y: 210 }
      - { x: -90, y: 240, radius: 36 }
      - { x: -110, y: 280 }
  - WaitForLeft
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome

$AutoStartRightScaleRightScaleRight:
  - $StartRightScaleRight
  - { parallel: true, name: $LiftSequenceScaleLowRight }
  - class: DrivePath
    reverse: true
    speed: 40
    path:
      - { x: 78, y: 204 }
      - { x: 90, y: 240, radius: 36 }
      - { x: 110, y: 280 }
  - WaitForRight
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome
  - { parallel: true, name: PickerPick }
  - class: DrivePath
    parallel: true
    speed: 80
    path:
      - { x: 110, y: 280, speed: 100.0 }
      - { x: 90, y: 240, radius: 36, speed: 40.0 }
      - { x: 52, y: 210 }
  - { parallel: true, name: $LiftSequenceScaleLowRight }
  - WaitForCube
  - class: DrivePath
    reverse: true
    speed: 40
    path:
      - { x: 52, y: 210 }
      - { x: 90, y: 240, radius: 36 }
      - { x: 110, y: 280 }
  - WaitForRight
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome

$AutoStartLeftScaleLeftSwitchLeft:
  - $StartLeftScaleLeft
  - { class: WaitFor, command: PickerPick }
  - { class: Wait, period: 1 }
  - { class: DriveStraight, angle: -38, distance: 12 }
  - PickerSwitchDeploy

$AutoStartRightScaleRightSwitchRight:
  - $StartRightScaleRight
  - { class: WaitFor, command: PickerPick }
  - { class: Wait, period: 1 }
  - { class: DriveStraight, angle: 38, distance: 12 }
  - PickerSwitchDeploy

$AutoStartRightScaleLeftScaleLeft:
  - $StartRightScaleLeft
  - { parallel: true, name: $LiftSequenceScaleLowLeft }
  - class: DrivePath
    reverse: true
    path:
      - { x: -82, y: 226, speed: 30 }
      - { x: -82, y: 238, radius: 36, speed: 30.0 }
      - { x: -102, y: 284, speed: 0 }
  - WaitForLeft
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome

$AutoStartLeftScaleRightScaleRight:
  - $StartLeftScaleRight
  - { parallel: true, name: $LiftSequenceScaleLowRight }
  - class: DrivePath
    reverse: true
    path:
      - { x: 82, y: 232, speed: 30.0 }
      - { x: 82, y: 244, radius: 36, speed: 20.0 }
      - { x: 102, y: 272, speed: 0 }
  - WaitForRight
  - PickerAutoDeploy
  - PivotCenter
  - $LiftHome

$AutoStartRightScaleLeftSwitchLeft:
  - $StartRightScaleLeft
  - { class: DriveStraight, angle: -38, distance: -8 }
  - { class: WaitFor, command: PickerPick }
  - { class: Wait, period: 1 }
  - { class: DriveStraight, angle: -38, distance: 18 }
  - PickerSwitchDeploy

$AutoStartLeftScaleRightSwitchRight:
  - $StartLeftScaleRight
  - { class: DriveStraight, angle: 30, distance: -8 }
  - { class: WaitFor, command: PickerPick }
  - { class: Wait, period: 0.5 }
  - { class: DriveStraight, angle: 30, distance: 23 }
  - PickerSwitchDeploy

$AutoStartRightScaleLeftSwitchRight:
  - $StartRightScaleLeft
  - PickerRetract
  - { class: DriveArc, angle: -90, radius: -36, endSpeed: 60 }
  - $LiftSwitchLow
  - { class: DriveStraight, angle: -90, distance: 65, endSpeed: 40 }
  - { class: DriveArc, angle: -60, arcLength: 30, speed: 40, endSpeed: 40 }
  - { class: DriveStraight, distance: 12 }
#  - { class: PickerQuickDeploy, timeBeforeKick: 0, timeToKick: .6, timeBeforeRetract: 0 }
  - PickerQuickDeploy

$AutoStartLeftScaleLeftSwitchRight:
  - $StartLeftScaleLeft
  - { class: WaitFor, command: PickerPick }
  - { class: DriveArc, angle: -90, radius: -36 }
  - $LiftSwitchLow
  - { class: DriveStraight, angle: -90, distance: 80, endSpeed: 40 }
  - { class: DriveArc, angle: -45, arcLength: 44, speed: 40, endSpeed: 40 }
#  - { class: PickerQuickDeploy, timeBeforeKick: 0, timeToKick: .6, timeBeforeRetract: 0 }
  - PickerQuickDeploy