DriveTank:
  modifiers: { deadzone: 0.1, exponent: 2.0 }

PickerPick:
  pickPowers: { left: 1.0, right: 0.5 }
  unjamPowers: { left: 0.4, right: -0.4 }
  holdPowers: { left: 0.1, right: 0.1 }
  jamDetectPeriod: 0.05
  unjamPeriod: 0.2
  afterUnjamWait: 0.5
  finishDetectPeriod: 0.0

PickerRelease:
  powers: { left: -1.0, right: -1.0 }

PivotLeft: { class: PivotAnglePreset, preset: LEFT }
PivotCenter: { class: PivotAnglePreset, preset: CENTER }
PivotRight: { class: PivotAnglePreset, preset: RIGHT }

LiftHome: { class: LiftHeightPreset, preset: HOME }
LiftPick: { class: LiftHeightPreset, preset: PICK }
LiftSwitch: { class: LiftHeightPreset, preset: SWITCH }
LiftScaleLow: { class: LiftHeightPreset, preset: SCALE_LOW }
LiftScaleHigh: { class: LiftHeightPreset, preset: SCALE_HIGH }

LiftContinuous:
  pivotSweepPower:
  startSweepAngle:
  sweepTimeout:
