operatorInterface:
  driverJoystick: { port: 0 }
  gunnerJoystick: { port: 1 }
  gunnerSecondary: { port: 2 }
  slider: { port: 3 }
  knobRange: 90
  knobDeadzone: 7
  sliderFunction: { minX: -1, minY: 0, maxX: 1, maxY: 85 }
drive:
  leftMotor:
    - { type: VICTOR_SP, channel: 0, inverted: true, powerChannels: [] }
    - { type: VICTOR_SPX, config: { id: 10, inverted: false } }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor:
    - { type: VICTOR_SP, channel: 1, inverted: false, powerChannels: [] }
    - { type: VICTOR_SPX, config: { id: 11, inverted: true } }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController:
      P: 0.05
      I: 0.0
      D: 0.0
      maxAbsoluteOutput: 0.5
  speedController:
      P: 0.015
      I: 0.0
      D: 0.0
      F: .0074
#      logData: true
  maxSpeed: 136
  straightMotionFollower:
      kpP: 1.0
      kiP: 0.0
      kpV: 0.015
      kfV: .0074
      kMinOutput: .082
      kfA: 0.004
      maxIError: 10.0
#      logData: true
  yawAngleController:
      P: 0.1
      I: 0.0
      D: -0.1
      maxIError: 12.0
  #    logData: true
  rotationMotionFollower:
      kpP: 0.15
      kiP: 0.5
      kpV: 0.01
      kfV: .01
      kMinOutput: .1087
      kfA: 0.0004
      maxIError: 2.0
  #    logData: true
  driveSegmentsFollower:
    lookAhead: { minX: 9, minY: 9, maxX: 120, maxY: 18 }
    logData: true
    speedFollower:
      kpP: 2.0
      kiP: 0.0
      kpV: 0.0
      kfV: 1.0
      kMinOutput: 0.0
      kfA: 0.05
      maxIError: 10.0
      maxAcceleration: 100.0
#      logData: true
  tankKinematics: { effectiveTrackWidth: 30.0 }
picker:
  leftMotor: { type: VICTOR_SPX, config: { id: 1 } }
  rightMotor: { type: VICTOR_SPX, config: { id: 2, inverted: true } }
  extensionSolenoid: { channel: 0 }
  cubeDetectSensor: { channel: 14, type: PNP }
  upperCubeSensor: { channel: 13, type: NPN }
  lowerCubeSensor: { channel: 12, type: NPN }
  armLock: { channel: 7 }
lift:
  liftMotor:
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
  liftEncoder: { aChannel: 4, bChannel: 5, reverse: false, distancePerPulse: 0.05249 }
  limitSensorTop: { channel: 11, type: NPN }
  limitSensorBottom: { channel: 10, type: NPN }

  heightController:
    kpP: 0.3
    kiP: 0.0 # 0.2
    kpV: 0.015
    maxIError: 5.0
    kfV: 0.009
    kMinOutput: 0.0823
    kfA: 0.00089
    kHoldPower: 0.129
    tolerance: 0.5
    maxOutput: 1.0
    minOutput: -0.5
    minPosition: 0.0
    maxPosition: 85.0
    maxAcceleration: 140.0
    travelVelocity: 80.0
    endVelocity: 0.0
#    logData: true

  heightPresets:
    HOME: 0
    PICK: 0
    NEED_LOCK: 6
    SWITCH_LOW: 12
    NEED_CENTER: 44
    SWITCH: 46
    SCALE_LOW: 64
    SCALE_HIGH: 76

  bumpHeightValue: 5
  heightTolerance: 2.0
  homeTolerance: 1.0
  homePower: -0.1
  homingTimeout: 2.0
  homingPower: -0.2
pivot:
  pivotMotor: { type: VICTOR_SPX, config: { id: 5, inverted: false } }
  pivotEncoder: { aChannel: 6, bChannel: 7, reverse: false, samplesToAverage: 50,
    distancePerPulse: 0.3515625 } # 360 degrees / 1024 CPR
  pivotLockSolenoid: { channel: 1 }
  pivotLockSensor: { channel: 16, type: PNP }

  pivotController:
    kpP: 0.15
    kiP: 0.0 # 0.04
    kpV: 0.00025
    kfV: 0.0015
    kMinOutput: 0.054
    kfA: 0.00075
    kHoldPower: 0.0
    minPosition: -90.0
    maxPosition: 90.0
    maxOutput: 0.8
    minOutput: -0.8
    maxAcceleration: 600.0
    travelVelocity: 200.0
    endVelocity: 0.0
#    logData: true
  pivotHoldPower: 0.15
  anglePresets:
    LEFT: -90
    HALF_LEFT: -45
    CENTER: 0
    HALF_RIGHT: 45
    RIGHT: 90

  bumpPivotValue: 15

  angleTolerance: 4.0
  centerTolerance: 15.0

  pivotSweepPower: 0.2
  startSweepAngle: 2.0
  lockAngle: 30
  sweepTimeoutSeconds: 5.0
  lockedPeriod: 0.1
auto:
  autoChoices: ["NoAuto", "LineCrossAuto", "Scale", "ScaleSwitch", "$CenterAuto", "SmartScale"]
  defaultChoice: "LineCrossAuto"
vision:
  width: 320
  height: 240
  contrast: 20
  saturation: 50
#  exposure: 3
  lowerThreshold: [18.0, 210.0, 170.0]
  upperThreshold: [34.0, 255.0, 255.0]
  minWidth: 41
  maxWidth: 130
  minHeight: 29
  maxHeight: 115
  distanceCalculator: { a: 137.87, b: 150.78, c: 71.129 }
  fovX: 30
  yawOffset: -4.0
climber:
  climberMotor:
    - type: TALON_SRX
      config:
        id: 6
        inverted: true
        feedbackDevice: CTRE_MagEncoder_Relative
        neutralToFullTime: 0.25
    - type: VICTOR_SPX
      config:
        id: 7
        inverted: true
        neutralToFullTime: 0.25
    - type: TALON_SRX # TODO: COMP_BOT: VICTOR_SPX
      config:
        id: 8
        inverted: false
        neutralToFullTime: 0.25
    - type: TALON_SRX # TODO: COMP_BOT: VICTOR_SPX
      config:
        id: 9
        inverted: false
        neutralToFullTime: 0.25
  topLimit: { channel: 17, type: NPN }
  bottomLimit: { channel: 15, type: NPN }
  releaser: { channel: 2 }
  distancePerPulse: -0.08518518518518519
