operatorInterface:
  driverJoystick: {index: 0, leftTriggerDeadzone: 0.1, rightTriggerDeadzone: 0.1}
  gunnerJoystick: {index: 1, leftTriggerDeadzone: 0.1, rightTriggerDeadzone: 0.1}
drive:
  leftMotor: { channel: 0, inverted: false, powerChannels: [] }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor: { channel: 1, inverted: true, powerChannels: [] }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController: {}
picker:
  leftMotor: { type: TALON_SRX, channel: 1 }
  rightMotor: { type: TALON_SRX, channel: 2, inverted: true }
  deathGripSolenoid: { channel: 7 }
  extensionSolenoid: { channel: 6 }
  cubeDetectSensor: { channel: 14 }
  cubeDetectLeftSensor: { channel: 13, type: NPN }
  cubeDetectRightSensor: { channel: 12, type: NPN }
  cubePresenseSensor: { channel: 15 }