operatorInterface:
  driverJoystick: { port: 0 }
  gunnerJoystick: { port: 1 }
drive:
  leftMotor: { type: VICTOR_SP, channel: 0, inverted: false, powerChannels: [] }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor: { type: VICTOR_SP, channel: 1, inverted: true, powerChannels: [] }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController: {}
  straightMotionFollower:
      kpP: 1.0
      kiP: 0.0
      kpV: 0.025
      kfV: .0077
      kMinOutput: .0461
      kfA: 0.0016
      maxIError: 10.0
  #    logData: true
  yawAngleController:
      P: 0.01
      I: 0.0
      D: 0.0
      F: 0.0
      maxIError: 12.0
  #    logData: true
  rotationMotionFollower:
      kpP: 0.1
      kiP: 0.5
      kpV: 0.005
      kfV: .0025
      kMinOutput: .1087
      kfA: 0.0004
      maxIError: 2.0
  #    logData: true
picker:
  leftMotor: { type: TALON_SRX, config: { id: 1 } }
  rightMotor: { type: TALON_SRX, config: { id: 2, inverted: true } }
  extensionSolenoid: { channel: 0 }
  cubeDetectSensor: { channel: 14, type: PNP }
  upperCubeSensor: { channel: 13, type: NPN }
  lowerCubeSensor: { channel: 12, type: NPN }
lift:
  liftMotor:
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
  liftEncoder: { aChannel: 4, bChannel: 5, reverse: false, distancePerPulse: 0.05249 }
  limitSensorTop: { channel: 11, type: NPN }
  limitSensorBottom: { channel: 10, type: NPN }
  pivotMotor: { type: VICTOR_SPX, config: { id: 5, inverted: false } }
  pivotEncoder: { channel: 0, fullRange: 360.0, offset: -237.5 }
  pivotLockSolenoid: { channel: 1 }
  pivotLockSensor: { channel: 16, type: PNP }

  heightController:
    kpP: 0.2
    kiP: 0.0
    kpV: 0.005
    kfV: 0.009
    kMinOutput: 0.0823
    kfA: 0.00089
    kHoldPower: 0.129
    maxOutput: 1.0
    minOutput: -0.5
    minPosition: 0.0
    maxPosition: 85.0
    maxAcceleration: 80.0
    travelVelocity: 60.0
    endVelocity: 0.0

  pivotController:
    P: 0.02 #0.2
    I: 0.04
    D: 0 #-0.08
    maxIError: 0.5
    maxAbsoluteSetpoint: 90.0
    maxAbsoluteOutput: 0.2
    target: { within: 2.0 }
    holdPower: 0.0

  anglePresetLeft: -90
  anglePresetCenter: 0
  anglePresetRight: 90
  heightBottomLimit: 0.0
  heightTopLimit: 85.0
  heightPresetPick: 2
  heightPresetSwitch: 46
  heightPresetScaleLow: 70
  heightPresetScaleHigh: 80
  heightPresetHome: 0

  bumpHeightValue: 1
  bumpPivotValue: 5

  heightTolerance: 2.0
  angleTolerance: 3.0
auto:
  autoChoices: ["NoAuto", "LineCrossAuto", "$Scale"]
  defaultChoice: "$Scale"