operatorInterface:
  driverJoystick: { port: 0 }
  gunnerJoystick: { port: 2 }
  gunnerSecondary: { port: 1 }
drive:
  leftMotor: { type: VICTOR_SP, channel: 0, inverted: false, powerChannels: [] }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor: { type: VICTOR_SP, channel: 1, inverted: true, powerChannels: [] }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController:
      P: 0.05
      I: 0.0
      D: 0.0
      maxAbsoluteOutput: 0.5
  straightMotionFollower:
      kpP: 1.0
      kiP: 0.0
      kpV: 0.015
      kfV: .0074
      kMinOutput: .0461
      kfA: 0.0025
      maxIError: 10.0
#      logData: true
  yawAngleController:
      P: 0.1
      I: 0.0
      D: -0.08
      maxIError: 12.0
  #    logData: true
  rotationMotionFollower:
      kpP: 0.15
      kiP: 0.5
      kpV: 0.01
      kfV: .01
      kMinOutput: .1087
      kfA: 0.0004
      maxIError: 2.0
  #    logData: true
  driveSegmentsFollower:
    lookAhead: { minX: 9, maxX: 9, minY: 120, maxY: 21 }
    speedFollower:
      kpP: 0.05
      kiP: 0.05
      kpV: 0.02
      kfV: .01
      kMinOutput: .0461
      kfA: 0.0025
      maxIError: 10.0
      maxAcceleration: 80.0
  tankKinematics: { effectiveTrackWidth: 36.0 }
picker:
  leftMotor: { type: VICTOR_SPX, config: { id: 1 } }
  rightMotor: { type: VICTOR_SPX, config: { id: 2, inverted: true } }
  extensionSolenoid: { channel: 0 }
  cubeDetectSensor: { channel: 14, type: PNP }
  upperCubeSensor: { channel: 13, type: NPN }
  lowerCubeSensor: { channel: 12, type: NPN }
lift:
  liftMotor:
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
  liftEncoder: { aChannel: 4, bChannel: 5, reverse: false, distancePerPulse: 0.05249 }
  limitSensorTop: { channel: 11, type: NPN }
  limitSensorBottom: { channel: 10, type: NPN }
  pivotMotor: { type: VICTOR_SPX, config: { id: 5, inverted: false } }
  pivotEncoder: {
    channel: 0, fullRange: 360.0, minValue: -180, continuous: true,
    averageBits: 4, oversampleBits: 4,
    offset: -133
  }
  pivotLockSolenoid: { channel: 1 }
  pivotLockSensor: { channel: 16, type: PNP }

  heightController:
    kpP: 0.2
    kiP: 0.0
    kpV: 0.005
    kfV: 0.009
    kMinOutput: 0.0823
    kfA: 0.00089
    kHoldPower: 0.129
    maxOutput: 1.0
    minOutput: -0.5
    minPosition: 0.0
    maxPosition: 85.0
    maxAcceleration: 140.0
    travelVelocity: 100.0
    endVelocity: 0.0

  pivotController:
#    kpP: 0.04 # 0.04
#    kiP: 0.0 # 0.04
#    kpV: 0.001
#    kfV: 0.002
#    kMinOutput: 0.0537
#    kfA: 0.0005
#    kHoldPower: 0.0
#    minPosition: -90.0
#    maxPosition: 90.0
#    maxOutput: 0.4
#    minOutput: -0.4
#    maxAcceleration: 180.0
#    travelVelocity: 90.0
#    endVelocity: 0.0
    target: { within: 3.0 }
    minSetpoint: -90.0
    maxSetpoint: 90.0
    maxAcceleration: 0.8
    movePower: 0.4
    endRamp: 20.0
#    logData: true

  pivotHoldPower: 0.15

  anglePresets:
    LEFT: -88
    HALF_LEFT: -45
    CENTER: 0
    HALF_RIGHT: 45
    RIGHT: 85
  heightPresetPick: 2
  heightPresetLowSwitch: 12
  heightPresetSwitch: 46
  heightPresetScaleLow: 58
  heightPresetScaleHigh: 70
  heightPresetHome: 0

  bumpHeightValue: 5
  bumpPivotValue: 15

  heightTolerance: 2.0
  angleTolerance: 4.0
auto:
  autoChoices: ["NoAuto", "LineCrossAuto", "Scale", "ScaleSwitch", "$CenterAuto"]
  defaultChoice: "$Scale"
vision:
  width: 320
  height: 240
  contrast: 20
  saturation: 50
#  exposure: 3
  lowerThreshold: [18.0, 210.0, 170.0]
  upperThreshold: [34.0, 255.0, 255.0]
  minWidth: 41
  maxWidth: 130
  minHeight: 29
  maxHeight: 115
  distanceCalculator: { a: 137.87, b: 150.78, c: 71.129 }
  fovX: 30
  yawOffset: -4.0
elevators:
    rightElevatorSolenoid: { channel: 4 }
    releaser: { channel: 2 }
    elevatorSlideSolenoid: { forwardChannel: 5, reverseChannel: 6 }
    leftFlap: { type: VICTOR_SPX, config: { id: 6, inverted: true } }
    leftFlapSensor: { channel: 15, type: NPN }
