operatorInterface:
  driverJoystick: { port: 0 }
  gunnerJoystick: { port: 1 }
  gunnerSecondary: { port: 2 }
  slider: { port: 3 }
  knobRange: 90
  knobDeadzone: 7
  sliderFunction: { minX: -1, minY: 0, maxX: 1, maxY: 85 }
drive:
  leftMotor: { type: VICTOR_SP, channel: 0, inverted: false, powerChannels: [] }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor: { type: VICTOR_SP, channel: 1, inverted: true, powerChannels: [] }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController:
      P: 0.05
      I: 0.0
      D: 0.0
      maxAbsoluteOutput: 0.5
  straightMotionFollower:
      kpP: 1.0
      kiP: 0.0
      kpV: 0.015
      kfV: .0074
      kMinOutput: .082
      kfA: 0.004
      maxIError: 10.0
#      logData: true
  yawAngleController:
      P: 0.1
      I: 0.0
      D: -0.1
      maxIError: 12.0
  #    logData: true
  rotationMotionFollower:
      kpP: 0.15
      kiP: 0.5
      kpV: 0.01
      kfV: .01
      kMinOutput: .1087
      kfA: 0.0004
      maxIError: 2.0
  #    logData: true
  driveSegmentsFollower:
    lookAhead: { minX: 9, minY: 9, maxX: 120, maxY: 21 }
    logData: true
    speedFollower:
      kpP: 0.4
      kiP: 0.2
      kpV: 0.04
      kfV: .0074
      kMinOutput: .082
      kfA: 0.004
      maxIError: 10.0
      maxAcceleration: 100.0
#      logData: true
  tankKinematics: { effectiveTrackWidth: 38.0 }
picker:
  leftMotor: { type: VICTOR_SPX, config: { id: 1 } }
  rightMotor: { type: VICTOR_SPX, config: { id: 2, inverted: true } }
  extensionSolenoid: { channel: 0 }
  cubeDetectSensor: { channel: 14, type: PNP }
  upperCubeSensor: { channel: 13, type: NPN }
  lowerCubeSensor: { channel: 12, type: NPN }
  armLock: { channel: 7 }
lift:
  liftMotor:
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
  liftEncoder: { aChannel: 4, bChannel: 5, reverse: false, distancePerPulse: 0.05249 }
  limitSensorTop: { channel: 11, type: NPN }
  limitSensorBottom: { channel: 10, type: NPN }

  heightController:
    kpP: 0.3
    kiP: 0.0 # 0.2
    kpV: 0.015
    maxIError: 5.0
    kfV: 0.009
    kMinOutput: 0.0823
    kfA: 0.00089
    kHoldPower: 0.129
    tolerance: 0.5
    maxOutput: 1.0
    minOutput: -0.5
    minPosition: 0.0
    maxPosition: 85.0
    maxAcceleration: 140.0
    travelVelocity: 80.0
    endVelocity: 0.0
#    logData: true

  heightPresets:
    HOME: 0
    PICK: 0
    NEED_LOCK: 6
    SWITCH_LOW: 12
    NEED_CENTER: 44
    SWITCH: 46
    SCALE_LOW: 58
    SCALE_HIGH: 70

  bumpHeightValue: 5
  heightTolerance: 2.0
  homeTolerance: 1.0
  homePower: -0.1
  homingTimeout: 2.0
  homingPower: -0.2
pivot:
  pivotMotor: { type: VICTOR_SPX, config: { id: 5, inverted: false } }
  pivotEncoder: {
    channel: 0, fullRange: 360.0, minValue: -180, continuous: true,
    averageBits: 4, oversampleBits: 4,
    offset: -42.5
  }
  pivotLockSolenoid: { channel: 1 }
  pivotLockSensor: { channel: 16, type: PNP }

  pivotController:
#    kpP: 0.04 # 0.04
#    kiP: 0.0 # 0.04
#    kpV: 0.001
#    kfV: 0.002
#    kMinOutput: 0.0537
#    kfA: 0.0005
#    kHoldPower: 0.0
#    minPosition: -90.0
#    maxPosition: 90.0
#    maxOutput: 0.4
#    minOutput: -0.4
#    maxAcceleration: 180.0
#    travelVelocity: 90.0
#    endVelocity: 0.0
    target: { within: 3.0 }
    minSetpoint: -90.0
    maxSetpoint: 90.0
    maxAcceleration: 1.2
    movePower: 0.4
    endRamp: 20.0
#    logData: true
  pivotHoldPower: 0.15
  anglePresets:
    LEFT: -90
    HALF_LEFT: -45
    CENTER: 0
    HALF_RIGHT: 45
    RIGHT: 90

  bumpPivotValue: 15

  angleTolerance: 4.0
  centerTolerance: 15.0

  pivotSweepPower: 0.2
  startSweepAngle: 5.0
  lockAngle: 30
  sweepTimeoutSeconds: 5.0
  lockedPeriod: 0.1
auto:
  autoChoices: ["NoAuto", "LineCrossAuto", "Scale", "ScaleSwitch", "$CenterAuto", "SmartScale"]
  defaultChoice: "LineCrossAuto"
vision:
  width: 320
  height: 240
  contrast: 20
  saturation: 50
#  exposure: 3
  lowerThreshold: [18.0, 210.0, 170.0]
  upperThreshold: [34.0, 255.0, 255.0]
  minWidth: 41
  maxWidth: 130
  minHeight: 29
  maxHeight: 115
  distanceCalculator: { a: 137.87, b: 150.78, c: 71.129 }
  fovX: 30
  yawOffset: -4.0
climber:
  climberMotor:
    - type: TALON_SRX
      config:
        id: 6
        inverted: true
        feedbackDevice: CTRE_MagEncoder_Relative
        neutralToFullTime: 0.25
    - type: VICTOR_SPX
      config:
        id: 7
        inverted: false
        neutralToFullTime: 0.25
    - type: VICTOR_SPX
      config:
        id: 8
        inverted: false
        neutralToFullTime: 0.25
    - type: VICTOR_SPX
      config:
        id: 9
        inverted: true
        neutralToFullTime: 0.25
  topLimit: { channel: 17, type: NPN }
  bottomLimit: { channel: 15, type: NPN }
  releaser: { channel: 2 }
  distancePerPulse: -0.08518518518518519
