operatorInterface:
  driverJoystick: { port: 0 }
  gunnerJoystick: { port: 1 }
drive:
  leftMotor: { type: VICTOR_SP, channel: 0, inverted: false, powerChannels: [] }
  leftEncoder: { aChannel: 0, bChannel: 1, reverse: true, distancePerPulse: .0471238898}
  rightMotor: { type: VICTOR_SP, channel: 1, inverted: true, powerChannels: [] }
  rightEncoder: { aChannel: 2, bChannel: 3, reverse: false, distancePerPulse: .0471238898}
  rotationController: {}
picker:
  leftMotor: { type: TALON_SRX, config: { id: 1 } }
  rightMotor: { type: TALON_SRX, config: { id: 2, inverted: true } }
  extensionSolenoid: { channel: 6 }
  cubeDetectSensor: { channel: 14, type: PNP }
  cubeDetectLeftSensor: { channel: 13, type: NPN }
  cubeDetectRightSensor: { channel: 12, type: NPN }
lift:
  liftMotor:
    - { type: VICTOR_SPX, config: { id: 3, inverted: false } }
    - { type: VICTOR_SPX, config: { id: 4, inverted: false } }
  liftEncoder: { aChannel: 4, bChannel: 5, reverse: false, distancePerPulse: 0.05249 }
  limitSensorTop: { channel: 11, type: NPN }
  limitSensorBottom: { channel: 10, type: NPN }
  pivotMotor: { type: VICTOR_SPX, config: { id: 5, inverted: false } }
  pivotEncoder: { channel: 3, fullRange: 360.0, offset: -211.4 }

  pivotController:
    P: 0.02
    I: 0.04
    D: 0.0
    maxIError: 0.5
    maxAbsoluteSetpoint: 90.0
    maxAbsoluteOutput: 0.2
    target: { within: 1.0 }
    holdPower: 0.0

  anglePresetLeft: 0
  anglePresetCenter: 0
  anglePresetRight: 0
  heightPresetPick: 0
  heightPresetSwitch: 0
  heightPresetScaleLow: 0
  heightPresetScaleHigh: 0
  heightPresetHome: 0

