defaults: [ DriveTank, LiftContinuous ]

driver:
  TRIGGER_RIGHT: toggle whenPressed PickerPick
  TRIGGER_LEFT: toggle whenPressed PickerSmartDeploy
  BUMPER_RIGHT: start whenPressed $LiftHome
  BUMPER_LEFT: start whenPressed $LiftSwitchLow
#  POV_UP: start whenPressed PivotCenter
  POV_LEFT: start whenPressed PivotLeft
  POV_RIGHT: start whenPressed PivotRight
#  POV_DOWN: start whenPressed $LiftSwitchLow
  POV_UP: start whenPressed BumpLiftUp
  POV_DOWN: start whenPressed BumpLiftDown
#  POV_LEFT: start whenPressed BumpPivotLeft
#  POV_RIGHT: start whenPressed BumpPivotRight
  A: start whenPressed $LiftHome
  START: start whenPressed PrintPose
  BACK: toggle whenPressed $TestDrive
#  START: start whenPressed $LiftScaleLow
#  BACK: start whenPressed $PickerReleaseMedium
#  B: start whenPressed $LiftSwitchLow
#  STICK_LEFT: start whenPressed PickerSwitchDeploy
#  B: start whenPressed $LiftSwitchLow
  B: start whenPressed ClimberClimb
  X: start whenPressed ClimberSubBar
  Y: start whenPressed ClimberOverBar
  STICK_LEFT: toggle whenPressed PickerRegrip
  STICK_RIGHT: start whenPressed PickerExtendToggle

gunner:
  LEFT_PINKY: start whenPressed PickerSwitchDeploy #whilePressed PickerReleaseSoft
  LEFT_MIDDLE:
    - start whenPressed PickerDefaultExtend
    - start whenReleased PickerDefaultRetract
  LEFT_RING: start whenPressed PivotLeft
  LEFT_INDEX: start whenPressed PivotRight
  LEFT_THUMB: start whenPressed PickerExtendToggle
  RIGHT_THUMB: start whenPressed $LiftHome
  RIGHT_INDEX: start whenPressed $LiftSwitchLow
  RIGHT_MIDDLE: start whenPressed $LiftScaleLow
  RIGHT_RING: toggle whenPressed PickerSmartDeploy
  RIGHT_PINKY:
    - start whenPressed ClimberRelease
    - start whenReleased ClimberUnrelease
gunnerSecondary:
  1: start whenPressed $PickerReleaseMedium
  2: toggle whenPressed ClimberOverBar
  3: toggle whenPressed ClimberSubBar
  4: toggle whenPressed PickerPick
  5: start whenPressed PickerRetract
  6: start whenPressed BumpPivotLeft
  7: start whenPressed BumpPivotRight
  8: start whenPressed $LiftSwitch
  9: start whenPressed $LiftScaleHigh
  10: start whenPressed PivotCenter
  12: start whenPressed LiftRecall
#  12: start whenPressed $PickerReleaseHard
