defaults: [ DriveTank, LiftContinuous ]

driver:
  TRIGGER_RIGHT: toggle whenPressed PickerPick
  TRIGGER_LEFT: start whenPressed $PickerReleaseHard
  BUMPER_RIGHT: toggle whenPressed $AutoPick
  POV_UP: start whenPressed PivotCenter
  POV_LEFT: start whenPressed PivotLeft
  POV_RIGHT: start whenPressed PivotRight
  POV_DOWN: start whenPressed $LiftSwitchLow
  A: start whenPressed $LiftHome
gunner:
  LEFT_PINKY: start whenPressed $PickerReleaseSoft
  LEFT_MIDDLE: start whenPressed PickerSwitchDeploy
  LEFT_RING: start whenPressed PivotLeft
  LEFT_INDEX: start whenPressed PivotRight
  LEFT_THUMB: toggle whenPressed PickerPick
  RIGHT_THUMB: start whenPressed $LiftHome
  RIGHT_INDEX: start whenPressed $LiftSwitchLow
  RIGHT_MIDDLE: start whenPressed $LiftSwitch
  RIGHT_RING: start whenPressed $LiftScaleLow
  RIGHT_PINKY: start whenPressed $LiftScaleHigh
gunnerSecondary:
  1: start whenPressed $PickerReleaseMedium
#  2: start whenPressed $TestDrive
#  3: start whenPressed PrintPose
  2: start whenPressed ElevatorsDeploy
  3: toggle whenPressed ElevatorsLiftLeft
  4: start whenPressed PickerExtend
  5: start whenPressed PickerRetract
  6: start whenPressed BumpPivotLeft
  7: start whenPressed BumpPivotRight
  8: start whenPressed BumpLiftUp
  9: start whenPressed BumpLiftDown
  10: start whenPressed PivotCenter
  11: start whenPressed ElevatorsLiftRight
  12: start whenPressed $PickerReleaseHard
